---
title: "Abgabe 3"
description: "Thema: Lebenserwartung"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(gganimate)
options(gganimate.nframes = 30)
library(gifski)
library(gapminder)
```

```{r, layout="l-body-outset", fig.width=8, fig.height=5}
gapminder %>%  
    filter(country %in% c("Germany", "France", "Spain", "Netherlands", "Belgium", "Portugal", "Luxemburg", "Poland")) %>% 
  # for each year we assign a rank
  group_by(year) %>%  
  arrange(year, -gdpPercap) %>%  # this is the variable we want to use for our race
  # assign ranking
  mutate(rank = 1:n()) %>% 
  filter(rank <= 10) -> # how many positions on the race?
  ranked_by_year

#Meine Lösung
ggplot(ranked_by_year) +
  aes(x = fct_reorder(country, lifeExp) , y = lifeExp, fill = country) +
  geom_col() +
  scale_y_continuous(name = "Life Expectation",limits = c(0,80)) +
  scale_x_discrete(name = "Country") +
  gganimate::transition_time(year) +
  labs (title = "Life Expectation in year: {frame_time}",
          subtitle = "Bar Chart Race") -> anim

animate(
  anim,
  fps = 15,
  nframes = 240,
  renderer = gifski_renderer()
)

```
