---
title: "Abgabe 1"
description: "Thema: Netflix & Klima"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggridges)

#Klima
dat <- read_rds("./datasets/lincoln_temps.rds")
summer_months <- filter(dat, month_long == "June" | month_long == "July" | month_long == "August")

#Netflix
netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')  %>% 
  separate(duration, c("duration", "duration_units"), " ", convert = TRUE)

# Jeden Eintrag mehrfach listen für jede Kategorie einmal
netflix_titles %>% separate_rows(listed_in, sep = ", ")

# Jeden Eintrag mehrfach listen für jeden Schauspieler einmal
netflix_titles %>% separate_rows(cast, sep = ", ")
```

```{r, layout="l-body-outset", fig.width=8, fig.height=5}

theme_set(
    theme_classic(base_size = 10)
)
#Anzahl der veröffentlichten Filme & Serien im Vergleich
plot1 <- ggplot(netflix_titles, aes(x=type))+
  geom_bar() +
     labs(x= "Netflix type", y = "Released movies & tv shows")

#Anzahl der veröffentlichten Filme ab 2005 (Balkendiagramm)
condition1 <- filter(netflix_titles, release_year >= 2005 & type == "Movie")
plot2 <- ggplot(condition1, aes(x=release_year, color=type))+
  geom_bar() +
    labs (x= "Release year", y = "Released movies")

#Anzahl der veröffentlichten Filme & Serien ab 2010 im Vergleich (Liniendiagramm)
condition2 <- filter(netflix_titles, release_year >= 2010)
plot3 <- ggplot(condition2, aes(x=release_year, color=type))+
   geom_line(stat = 'count') +
      labs (x= "Release year", y = "Released movies & tv shows")

library(patchwork)

(plot1 + plot2 ) / plot3 +
  plot_annotation(title = "Netflix: Filme & Serien")
```

```{r, layout="l-body-outset", fig.width=8, fig.height=5}

ggplot(summer_months, aes(x = mean_temp, y = month_long)) +
  geom_density_ridges(
    fill = "gold1"
  ) +
    labs (title = "Temeraturverteilungen in den Sommermonaten",
          subtitle = "Ridgeline Plot",
          caption = "Höchsttemperatur im Juli",
          x = "Temperaturen (°F)",
          y = "Sommermonate")
```
